platform:
    - x64

cache:
    - C:\Users\appveyor\.esy

# Needed for running unit tests - blocked by ??
environment:
    ESY_NODE_PATH: C:/Program Files/nodejs/node.exe

install:
    # The x64 is required as a workaround for esy/esy#412
    - ps: Install-Product node 8 x64
    - npm install -g jest-cli
    - npm install -g esy@0.2.11
      # Workaround for issue fixed in bryphe/esy-bash#18
    - cp scripts/build/patched-bash-exec.js C:/Users/appveyor/AppData/Roaming/npm/node_modules/esy/node_modules/esy-bash/bash-exec.js
    - appveyor-retry appveyor-retry esy install

build_script:
     - npm run build
     - npm run test:e2e
     - npm run test:unit
     - npm run make:platform-release-package

artifacts:
    - path: _platformrelease/*.tgz
      name: Windows Build
      type: File

deploy:
    - provider: GitHub
      repository: esy/esy
      auth_token:
          secure: J4V6+1KHu8UiApItmxPWArb5oMf1WnQyAc9H4GtBzEo620zFin0oRLYQ0DxCz1VW
      draft: false
      prerelease: false
      force_update: true
      on:
          appveyor_repo_tag: true

test: off
